In [199]:
import numpy as np
import pandas as pd

In [200]:
ph_df=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Photohide/HIDE OUT ACTIVITY.xlsx")

In [201]:
ph_df.rename(columns={"Unnamed: 0":"Date","Unnamed: 1":"Type of animal","Unnamed: 2":"Quantity","Unnamed: 3":"Time in","Unnamed: 4":"Time out","Unnamed: 5":"Mins. Spent"}, inplace=True)
ph_df.head()

,Date,Type of animal,Quantity,Time in,Time out,Mins. Spent,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,2025-05-02 01:01:01,Lesser Kudu,1,2025-01-06 07:56:00,2025-01-06 09:11:00,01:15:00,NaN,NaN,NaN,NaN
1,2025-05-02 01:01:01,Elands,15,2025-01-06 09:08:00,2025-01-06 09:44:00,00:36:00,NaN,NaN,NaN,NaN
2,2025-05-02 01:01:01,Elephants,6,2025-01-06 21:26:30,2025-01-06 22:35:00,01:08:30,NaN,NaN,NaN,NaN
3,2025-05-03 01:01:01,Elands,1,2025-01-06 06:58:11,2025-01-06 08:11:00,01:12:49,NaN,NaN,NaN,NaN
4,2025-05-03 01:01:01,Impala,5,2025-01-06 09:30:01,2025-01-06 10:24:08,00:54:07,NaN,NaN,NaN,NaN

In [202]:
ph_df.drop(columns=["Unnamed: 6","Unnamed: 7","Unnamed: 8","Unnamed: 9"], inplace=True)
ph_df.head()

,Date,Type of animal,Quantity,Time in,Time out,Mins. Spent
0,2025-05-02 01:01:01,Lesser Kudu,1,2025-01-06 07:56:00,2025-01-06 09:11:00,01:15:00
1,2025-05-02 01:01:01,Elands,15,2025-01-06 09:08:00,2025-01-06 09:44:00,00:36:00
2,2025-05-02 01:01:01,Elephants,6,2025-01-06 21:26:30,2025-01-06 22:35:00,01:08:30
3,2025-05-03 01:01:01,Elands,1,2025-01-06 06:58:11,2025-01-06 08:11:00,01:12:49
4,2025-05-03 01:01:01,Impala,5,2025-01-06 09:30:01,2025-01-06 10:24:08,00:54:07

In [ ]:
ph_df['Quantity']=pd.to_numeric(ph_df['Quantity'],errors='ignore')

In [204]:
ph_df.drop(index=[0,1,2], inplace=True)
ph_df.head()

,Date,Type of animal,Quantity,Time in,Time out,Mins. Spent
3,2025-05-03 01:01:01,Elands,1,2025-01-06 06:58:11,2025-01-06 08:11:00,01:12:49
4,2025-05-03 01:01:01,Impala,5,2025-01-06 09:30:01,2025-01-06 10:24:08,00:54:07
5,2025-05-03 01:01:01,Grants gazelle,1,2025-01-06 20:49:00,2025-01-06 21:04:00,00:15:00
6,2025-05-04 01:01:01,Grants gazelle,1,2025-01-06 04:16:00,2025-01-06 04:37:00,00:21:00
7,2025-05-04 01:01:01,Elands,4,2025-01-06 06:51:00,2025-01-06 07:35:00,00:44:00

In [205]:
total_appearances=pd.DataFrame(ph_df.groupby('Type of animal')['Date'].count())
total_appearances=total_appearances.sort_values(by=['Date'],ascending=False)
mostcommon=total_appearances.head(20)

In [206]:
ph_df['Mins. Spent']=pd.to_timedelta(ph_df['Mins. Spent'].astype(str),errors='coerce')
ph_df['Date']=pd.to_datetime(ph_df['Date'].astype(str),errors='coerce')
ph_df['S_Date']=ph_df['Date'].astype(str)
ph_df['Time in']=pd.to_datetime(ph_df['Time in'].astype(str),errors='coerce')
ph_df['Time out']=pd.to_datetime(ph_df['Time out'].astype(str),errors='coerce')
ph_df['Quantity']=pd.to_numeric(ph_df['Quantity'],errors='coerce')
ph_df.head()

,Date,Type of animal,Quantity,Time in,Time out,Mins. Spent,S_Date
3,2025-05-03 01:01:01,Elands,1.0,2025-01-06 06:58:11,2025-01-06 08:11:00,0 days 01:12:49,2025-05-03 01:01:01
4,2025-05-03 01:01:01,Impala,5.0,2025-01-06 09:30:01,2025-01-06 10:24:08,0 days 00:54:07,2025-05-03 01:01:01
5,2025-05-03 01:01:01,Grants gazelle,1.0,2025-01-06 20:49:00,2025-01-06 21:04:00,0 days 00:15:00,2025-05-03 01:01:01
6,2025-05-04 01:01:01,Grants gazelle,1.0,2025-01-06 04:16:00,2025-01-06 04:37:00,0 days 00:21:00,2025-05-04 01:01:01
7,2025-05-04 01:01:01,Elands,4.0,2025-01-06 06:51:00,2025-01-06 07:35:00,0 days 00:44:00,2025-05-04 01:01:01

In [ ]:
animalsmonthly=pd.DataFrame(ph_df.groupby(pd.Grouper(key='Date',freq='M'))['Quantity'].agg([np.sum,np.mean]))
#drop data that is equal to 0
animalsmonthly=animalsmonthly.drop(animalsmonthly.index[animalsmonthly['sum']==0.0])
animalsmonthly.head(60)

In [208]:
#analysis on a weekly basis
animalsWeekly=pd.DataFrame(ph_df.groupby(pd.Grouper(key='Date',freq='W'))['Quantity'].agg([np.sum,np.mean]))
animalsWeekly=animalsWeekly.drop(animalsWeekly.index[animalsWeekly['sum']==0.0])
animalsWeekly.head(20)

/tmp/ipykernel_1579/2773718910.py:2: FutureWarning: The provided callable <function sum at 0x794aae795300> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  animalsWeekly=pd.DataFrame(ph_df.groupby(pd.Grouper(key='Date',freq='W'))['Quantity'].agg([np.sum,np.mean]))
/tmp/ipykernel_1579/2773718910.py:2: FutureWarning: The provided callable <function mean at 0x794aae7963e0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  animalsWeekly=pd.DataFrame(ph_df.groupby(pd.Grouper(key='Date',freq='W'))['Quantity'].agg([np.sum,np.mean]))

              sum       mean
Date
1900-01-07   56.0  11.200000
2025-05-04   14.0   2.000000
2025-05-11  136.0   4.857143
2025-05-18  124.0   4.960000
2025-05-25  192.0   6.193548
2025-06-01  246.0   5.020408
2025-06-08  205.0   5.125000
2025-06-15  197.0   4.804878
2025-06-22  347.0   7.382979
2025-06-29  394.0  11.257143
2025-07-06  247.0   6.500000
2025-07-13  458.0  10.409091
2025-07-20  258.0   8.896552
2025-07-27  269.0   9.275862
2025-08-03  290.0  11.153846
2025-08-10  384.0  10.666667
2025-08-17  385.0   7.000000
2025-08-24  400.0   7.142857
2025-08-31  332.0   5.533333
2025-09-07  376.0   4.700000

In [209]:
ph_df['Mins. Spent']=pd.to_timedelta(ph_df['Mins. Spent'],unit='Minutes')
#average_time=pd.DataFrame(ph_df.groupby([(pd.Grouper(key='Mins. Spent',freq='T')),'Type of animal'])[''])
average_time=pd.DataFrame(ph_df.groupby('Type of animal')['Mins. Spent'].agg(np.mean))

average_time.head(30)

/tmp/ipykernel_1579/1407907806.py:3: FutureWarning: The provided callable <function mean at 0x794aae7963e0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  average_time=pd.DataFrame(ph_df.groupby('Type of animal')['Mins. Spent'].agg(np.mean))

                               Mins. Spent
Type of animal
Baboon                     0 days 00:28:45
Baboons                    0 days 01:14:40
Banded Mongoose            0 days 00:06:45
Buffallo         0 days 00:15:51.176470588
Buffalo          0 days 00:11:49.846153846
Bushbacks                  0 days 01:21:00
Eagle            0 days 00:25:51.666666666
Egyptian Geese   0 days 00:17:08.571428571
Egyptian Goose             0 days 00:10:00
Elands           0 days 00:45:27.556521739
Elephants        0 days 00:27:30.823529411
Giraffe                    0 days 00:10:00
Grants gazelle   0 days 00:32:49.411764705
Hartebeest       0 days 00:50:12.115384615
Impala           0 days 01:01:03.312925170
Leopard                    0 days 00:04:00
Leopard tortoise           0 days 00:10:00
Lesser Kudu                0 days 00:44:46
Lesser kudu      0 days 01:21:32.727272727
Lions               0 days 00:22:53.437500
Owl              0 days 00:08:10.714285714
Secretary Bird   0 days 00:13:08.235294117
Serval Cat                 0 days 00:06:30
Serval cat       0 days 00:08:36.521739130
Spotted Hyena    0 days 00:10:20.808510638
Spotted Thicknee           0 days 00:14:00
Stork               0 days 00:26:07.500000
Striped Hyena              0 days 00:05:20
Tawny Eagle                0 days 00:27:00
Warthog          0 days 00:12:32.990909090

In [210]:
#find time most likely for each animal to appear
time_in=pd.DataFrame(ph_df.groupby(['Type of animal',(pd.Grouper(key='Time in',freq='H'))])['Quantity'].agg('median'))
time_in.head(60)
#list(time_in)
#time_in=time_in.groupby(pd.Grouper(key='Time in',freq='H'))['Quantity'].agg(np.sum)

/tmp/ipykernel_1579/1465129423.py:2: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  time_in=pd.DataFrame(ph_df.groupby(['Type of animal',(pd.Grouper(key='Time in',freq='H'))])['Quantity'].agg('median'))

                                     Quantity
Type of animal  Time in
Baboon          2025-01-06 09:00:00      20.0
                2025-01-06 11:00:00      17.5
                2025-01-06 12:00:00      20.0
Baboons         2025-01-06 08:00:00      20.0
                2025-01-06 10:00:00      12.0
Banded Mongoose 2025-01-06 10:00:00      16.0
                2025-01-06 19:00:00       1.0
                2025-01-06 20:00:00       1.0
                2025-01-06 23:00:00       1.0
Buffallo        2025-01-06 00:00:00       1.0
                2025-01-06 01:00:00       1.0
                2025-01-06 04:00:00       1.0
                2025-01-06 05:00:00       1.0
                2025-01-06 06:00:00       1.0
                2025-01-06 08:00:00       1.0
                2025-01-06 12:00:00       1.0
                2025-01-06 16:00:00       1.0
                2025-01-06 18:00:00       1.0
                2025-01-06 19:00:00       1.0
                2025-01-06 20:00:00       1.0
                2025-01-06 21:00:00       1.0
                2025-01-06 22:00:00       1.0
                2025-01-06 23:00:00       1.0
Buffalo         2025-01-06 00:00:00       1.0
                2025-01-06 03:00:00       1.0
                2025-01-06 04:00:00       1.0
                2025-01-06 06:00:00       1.5
                2025-01-06 07:00:00       1.0
                2025-01-06 08:00:00       1.0
                2025-01-06 09:00:00       1.5
                2025-01-06 10:00:00       1.0
                2025-01-06 13:00:00       1.0
                2025-01-06 17:00:00       1.0
                2025-01-06 18:00:00       1.0
                2025-01-06 19:00:00       1.0
                2025-01-06 20:00:00       2.0
                2025-01-06 21:00:00       1.0
                2025-01-06 22:00:00       1.0
                2025-01-06 23:00:00       1.5
Bushbacks       2025-01-06 22:00:00       1.0
                2025-01-06 23:00:00       1.0
Eagle           2025-01-06 03:00:00       1.0
                2025-01-06 07:00:00       1.0
                2025-01-06 08:00:00       1.0
                2025-01-06 09:00:00       1.0
                2025-01-06 10:00:00       1.0
                2025-01-06 11:00:00       1.0
                2025-01-06 12:00:00       1.0
                2025-01-06 13:00:00       1.0
                2025-01-06 14:00:00       1.0
                2025-01-06 15:00:00       1.0
                2025-01-06 16:00:00       1.0
                2025-01-06 17:00:00       1.0
Egyptian Geese  2025-01-06 05:00:00       2.0
                2025-01-06 06:00:00       2.0
                2025-01-06 07:00:00       2.0
                2025-01-06 14:00:00       1.0
                2025-01-06 17:00:00       2.0
Egyptian Goose  2025-01-06 06:00:00       4.0
Elands          2025-01-06 00:00:00       5.0

In [211]:
ph_df.head()
print(ph_df['Type of animal'].unique())

['Elands' 'Impala' 'Grants gazelle' 'Warthog' 'Hartebeest' 'Lesser Kudu'
 'Buffallo' nan 'Elephants' 'Lions' 'Giraffe' 'Buffalo' 'Eagle' 'Zebra'
 'Leopard tortoise' 'Banded Mongoose' 'Egyptian Geese' 'Leopard' 'baboons'
 'owl' 'White tailed Mongoose' 'Spotted Thicknee' 'Tawny Eagle'
 'Spotted Hyena' 'Stork' 'Serval cat' 'Waterbuck' 'Wildebeest' 'Owl'
 'Secretary Bird' 'Striped Hyena' 'zebra' 'gnu' 'baboon' 'Baboons' 'b'
 'Lesser kudu' 'Baboon' 'Egyptian Goose' 'impala' 'Serval Cat' 'Bushbacks'
 'White-tailed moongose']

In [212]:
lk_df=ph_df[ph_df['Type of animal']=='Lesser Kudu']
eland_df=ph_df[ph_df['Type of animal']=='Elands']
elephants_df=ph_df[ph_df['Type of animal']=='Elephants']
impala_df=ph_df[ph_df['Type of animal']=='Impala']
gg_df=ph_df[ph_df['Type of animal']=='Grants gazelle']
warthog_df=ph_df[ph_df['Type of animal']=='Warthog']
hartebeest_df=ph_df[ph_df['Type of animal']=='Hartebeest']
buffallo_df=ph_df[ph_df['Type of animal']=='Buffallo']
lions_df=ph_df[ph_df['Type of animal']=='Lions']
zebra_df=ph_df[ph_df['Type of animal']=='Zebra']
l_tortoise_df=ph_df[ph_df['Type of animal']=='Leopard tortoise']
b_mongoose_df=ph_df[ph_df['Type of animal']=='Banded Mongoose']
e_geese_df=ph_df[ph_df['Type of animal']=='Egyptian Geese']
leopard_df=ph_df[ph_df['Type of animal']=='Leopard']
lk_df.head(10)

,Date,Type of animal,Quantity,Time in,Time out,Mins. Spent,S_Date
14,2025-05-05 01:01:01,Lesser Kudu,1.0,2025-01-06 10:06:00,2025-01-06 10:32:00,0 days 00:26:00,2025-05-05 01:01:01
15,2025-05-05 01:01:01,Lesser Kudu,1.0,2025-01-06 17:16:00,2025-01-06 17:33:00,0 days 00:17:00,2025-05-05 01:01:01
35,2025-05-11 01:01:01,Lesser Kudu,1.0,2025-01-06 00:30:00,2025-01-06 01:48:00,0 days 01:18:00,2025-05-11 01:01:01
37,2025-05-11 01:01:01,Lesser Kudu,2.0,2025-01-06 13:54:00,2025-01-06 14:13:00,0 days 00:19:00,2025-05-11 01:01:01
39,2025-05-12 01:01:01,Lesser Kudu,1.0,2025-01-06 00:00:00,2025-01-06 00:16:00,0 days 00:16:00,2025-05-12 01:01:01
40,2025-05-12 01:01:01,Lesser Kudu,1.0,2025-01-06 02:47:00,2025-01-06 03:45:00,0 days 00:58:00,2025-05-12 01:01:01
42,2025-05-12 01:01:01,Lesser Kudu,1.0,2025-01-06 05:54:00,2025-01-06 06:50:00,0 days 00:56:00,2025-05-12 01:01:01
43,2025-05-12 01:01:01,Lesser Kudu,2.0,2025-01-06 07:58:00,2025-01-06 09:11:00,0 days 01:13:00,2025-05-12 01:01:01
49,2025-05-14 01:01:01,Lesser Kudu,1.0,2025-01-06 00:59:00,2025-01-06 01:47:00,0 days 00:48:00,2025-05-14 01:01:01
51,2025-05-16 01:01:01,Lesser Kudu,1.0,2025-01-06 00:01:00,2025-01-06 00:30:00,0 days 00:29:00,2025-05-16 01:01:01

In [213]:
total_appearances
#total appearances can make a histogram

                       Date
Type of animal
Zebra                   835
Elephants               265
Spotted Hyena           241
Impala                  153
Elands                  115
Warthog                 113
Hartebeest              109
Serval cat               96
Lesser Kudu              66
Lions                    64
Wildebeest               56
Secretary Bird           54
Eagle                    36
Buffallo                 34
Owl                      30
Buffalo                  28
Grants gazelle           18
White tailed Mongoose    16
Lesser kudu              12
impala                   11
Leopard tortoise          8
Stork                     8
owl                       7
Egyptian Geese            7
Giraffe                   7
Baboon                    4
Banded Mongoose           4
zebra                     3
Baboons                   3
Bushbacks                 3
Striped Hyena             3
baboons                   3
Serval Cat                2
Leopard                   2
Egyptian Goose            1
Spotted Thicknee          1
Tawny Eagle               1
Waterbuck                 1
White-tailed moongose     1
b                         1
baboon                    1
gnu                       1